### PR TITLE
Install awscli on build

### PR DESCRIPTION
**Pull request by wee007**

### CODE REVIEW

**Comment by Owenhorner** [comment]
whenever we use awscli do we need to configure it? Is there a way to configure keys in the Dockerfile?

**Comment by wee007** [comment]
Yes, we need to configure it once. Not sure if it can be configured in the Dockerfile.

**Comment by wee007** [comment]
I take that back - We would need to somehow configure AWS as part of the build otherwise we would need manually configure it for each build.

**Comment by qnm** [comment]
@owenhorner We don’t store keys in repositories. Also note this is a public repo so take double care.

If you need to use awscli, you log in.

**Pull request merged**
